# Generated by Django 3.0.4 on 2020-03-27 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200317_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c19apipatientprofile',
            options={'verbose_name': 'Covid-19 API Patient Profile', 'verbose_name_plural': 'Covid-19 API Patient Profiles'},
        ),
        migrations.AlterField(
            model_name='c19apipatientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c19_api_patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
